# Generated by Django 2.2.28 on 2024-01-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20240105_2015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
