# Generated by Django 2.2.28 on 2024-01-06 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20240106_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='department_id',
        ),
    ]
