# Generated by Django 2.2.28 on 2024-01-06 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('students', '0011_auto_20240106_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department_id',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.Department'),
        ),
    ]
