# Generated by Django 2.2.28 on 2024-01-07 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_auto_20240107_2213'),
        ('students', '0017_auto_20240106_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enroll_year',
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.EnrollmentYear'),
            preserve_default=False,
        ),
    ]
