# Generated by Django 2.2.28 on 2024-01-09 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_auto_20240109_0709'),
        ('students', '0018_auto_20240107_2213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
