# Generated by Django 2.2.28 on 2024-01-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_auto_20240109_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='roll_number',
            field=models.IntegerField(),
        ),
    ]
