# Generated by Django 4.2.9 on 2024-01-15 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0032_alter_enrollmentyears_academic_year_and_more'),
        ('students', '0022_students_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.sections'),
        ),
    ]
