# Generated by Django 4.2.9 on 2024-01-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_alter_students_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='roll_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
