# Generated by Django 2.2.28 on 2024-01-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_enrollyear'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnrollYear',
            new_name='Enroll_Year',
        ),
    ]
