# Generated by Django 2.2.28 on 2024-01-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_auto_20240107_2052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enroll_Year',
            new_name='EnrollYear',
        ),
    ]
