# Generated by Django 2.2.28 on 2024-01-07 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20240106_0422'),
        ('masters', '0004_auto_20240107_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Department')),
            ],
        ),
        migrations.RenameModel(
            old_name='EnrollYear',
            new_name='EnrollmentYear',
        ),
        migrations.CreateModel(
            name='TimetableDepartmentYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('period_no', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Timetable')),
            ],
        ),
        migrations.AddField(
            model_name='timetable',
            name='enrollment_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.EnrollmentYear'),
        ),
    ]
