# Generated by Django 2.2.28 on 2024-01-08 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_auto_20240107_2213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimetableDepartmentYear',
            new_name='TimetableDetail',
        ),
    ]
