# Generated by Django 2.2.28 on 2024-01-09 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20240107_2213'),
        ('masters', '0006_auto_20240108_1935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Departments',
        ),
        migrations.RenameModel(
            old_name='EnrollmentYear',
            new_name='EnrollmentYears',
        ),
        migrations.RenameModel(
            old_name='TimetableDetail',
            new_name='TimetableDetails',
        ),
        migrations.RenameModel(
            old_name='Timetable',
            new_name='Timetables',
        ),
    ]
