# Generated by Django 2.2.28 on 2024-01-10 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_auto_20240109_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='timetables',
            name='weekday',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Wednesday', max_length=10),
        ),
        migrations.CreateModel(
            name='HolidayDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('holiday_name', models.CharField(max_length=255)),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Holidays')),
            ],
        ),
    ]
