# Generated by Django 2.2.28 on 2024-01-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_auto_20240110_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetables',
            name='weekday',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Thursday', max_length=10),
        ),
    ]
