# Generated by Django 2.2.28 on 2024-01-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_auto_20240111_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentyears',
            name='current_year',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('Graduated', 'Graduated')], default='Graduated', max_length=10),
        ),
    ]
