# Generated by Django 2.2.28 on 2024-01-11 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0015_auto_20240111_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='department_id',
        ),
        migrations.AddField(
            model_name='subjects',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='masters.Departments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetables',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='masters.Sections'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holidaydetails',
            name='holiday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.Holidays'),
        ),
        migrations.AlterField(
            model_name='timetabledetails',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.Timetables'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.Departments'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='enrollment_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.EnrollmentYears'),
        ),
    ]
