# Generated by Django 2.2.28 on 2024-01-11 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_auto_20240111_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetabledetails',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='timetabledetails',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='masters.Subjects'),
            preserve_default=False,
        ),
    ]
