# Generated by Django 2.2.28 on 2024-01-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0017_auto_20240111_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='academic_year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], default='1st Year', max_length=10),
        ),
    ]
