# Generated by Django 2.2.28 on 2024-01-11 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0020_auto_20240111_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='code',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='name',
        ),
        migrations.AlterField(
            model_name='subjects',
            name='academic_year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='SubjectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.Subjects')),
            ],
        ),
    ]
