# Generated by Django 2.2.28 on 2024-01-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0022_auto_20240111_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetabledetails',
            old_name='subject_details',
            new_name='subject_detail',
        ),
    ]
