# Generated by Django 2.2.28 on 2024-01-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0024_auto_20240111_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyears',
            name='academic_year',
            field=models.CharField(max_length=255),
        ),
    ]
