# Generated by Django 2.2.28 on 2024-01-11 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0025_auto_20240111_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetables',
            name='enrollment_year',
        ),
        migrations.AddField(
            model_name='timetables',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='masters.AcademicYears'),
            preserve_default=False,
        ),
    ]
