# Generated by Django 2.2.28 on 2024-01-12 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0026_auto_20240111_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetables',
            name='academic_year',
        ),
        migrations.AddField(
            model_name='timetables',
            name='enrollment_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='masters.EnrollmentYears'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetables',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=1),
        ),
    ]
