# Generated by Django 4.2.9 on 2024-01-12 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0028_alter_academicyears_id_alter_departments_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaydetails',
            name='holiday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.holidays'),
        ),
        migrations.AlterField(
            model_name='subjectdetails',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.subjects'),
        ),
        migrations.AlterField(
            model_name='timetabledetails',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.timetables'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.departments'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='enrollment_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.enrollmentyears'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.sections'),
        ),
    ]
