# Generated by Django 4.2.9 on 2024-01-12 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0029_alter_holidaydetails_holiday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetables',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='masters.departments'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetables',
            name='enrollment_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='masters.enrollmentyears'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetables',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='masters.sections'),
            preserve_default=False,
        ),
    ]
