# Generated by Django 4.2.9 on 2024-01-15 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0031_alter_timetables_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentyears',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.academicyears'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.academicyears'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.departments'),
        ),
        migrations.AlterField(
            model_name='timetabledetails',
            name='subject_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.subjectdetails'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.departments'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='enrollment_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.enrollmentyears'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.sections'),
        ),
    ]
