# Generated by Django 2.2.28 on 2024-01-12 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0022_students_section'),
        ('masters', '0027_auto_20240112_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.Departments')),
                ('enrollment_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.EnrollmentYears')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.Sections')),
                ('timetable_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.TimetableDetails')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('attendance_type', models.IntegerField(choices=[(1, 'Manual'), (2, 'Face Scan')], default=1)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendances.Attendances')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.Students')),
            ],
        ),
    ]
