# Generated by Django 4.2.9 on 2024-01-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attendances',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
