# Generated by Django 4.2.9 on 2024-01-12 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0030_alter_timetables_department_and_more'),
        ('attendances', '0002_alter_attendancedetails_id_alter_attendances_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendances',
            name='timetable_detail',
        ),
        migrations.AddField(
            model_name='attendances',
            name='timetable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='masters.timetables'),
            preserve_default=False,
        ),
    ]
