# Generated by Django 4.2.9 on 2024-01-12 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0030_alter_timetables_department_and_more'),
        ('attendances', '0005_rename_in_datetime_attendancedetails_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedetails',
            name='timetable_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='masters.timetabledetails'),
            preserve_default=False,
        ),
    ]
