# Generated by Django 4.2.9 on 2024-01-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0006_attendancedetails_timetable_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancedetails',
            name='datetime',
        ),
        migrations.AddField(
            model_name='attendancedetails',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='attendancedetails',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
