# Generated by Django 4.2.9 on 2024-01-15 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_students_section'),
        ('masters', '0031_alter_timetables_weekday'),
        ('attendances', '0008_alter_attendances_weekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTimetableDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendances.attendances')),
                ('timetable_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.timetabledetails')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceTimetableDetailStudents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('attendance_type', models.IntegerField(choices=[(1, 'Manual'), (2, 'Face Scan')], default=1)),
                ('attendance_timetable_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendances.attendancetimetabledetails')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.students')),
            ],
        ),
    ]
