# Generated by Django 4.2.9 on 2024-01-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0009_attendancetimetabledetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendances',
            name='time',
        ),
        migrations.DeleteModel(
            name='AttendanceDetails',
        ),
    ]
