# Generated by Django 4.2.9 on 2024-01-15 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_alter_students_section'),
        ('masters', '0032_alter_enrollmentyears_academic_year_and_more'),
        ('attendances', '0010_remove_attendances_time_delete_attendancedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendances',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.departments'),
        ),
        migrations.AlterField(
            model_name='attendances',
            name='enrollment_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.enrollmentyears'),
        ),
        migrations.AlterField(
            model_name='attendances',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.sections'),
        ),
        migrations.AlterField(
            model_name='attendances',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.timetables'),
        ),
        migrations.AlterField(
            model_name='attendancetimetabledetails',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendances.attendances'),
        ),
        migrations.AlterField(
            model_name='attendancetimetabledetails',
            name='timetable_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.timetabledetails'),
        ),
        migrations.AlterField(
            model_name='attendancetimetabledetailstudents',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students'),
        ),
    ]
