# Generated by Django 2.2.28 on 2024-01-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSettings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rows_per_page', models.PositiveIntegerField(default=10)),
                ('topbar_link', models.URLField(blank=True, null=True)),
                ('topbar_link_text', models.CharField(blank=True, max_length=255, null=True)),
                ('sidebar_icon', models.ImageField(blank=True, null=True, upload_to='images/sidebar_icons/')),
                ('sidebar_text', models.CharField(blank=True, max_length=255, null=True)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='images/favicons/')),
            ],
        ),
    ]
