# Generated by Django 2.2.28 on 2024-01-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationsettings',
            name='topbar_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
