# Generated by Django 2.2.28 on 2024-01-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_configurations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configurations',
            old_name='name',
            new_name='label',
        ),
    ]
