# Generated by Django 2.2.28 on 2024-01-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20240111_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configurations',
        ),
    ]
