# Generated by Django 2.2.28 on 2024-01-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_delete_configurations'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationsettings',
            name='user_icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/user_icons/'),
        ),
        migrations.AddField(
            model_name='configurationsettings',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
