# Generated by Django 2.2.28 on 2024-01-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20240111_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationsettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='images/icons/'),
        ),
        migrations.AlterField(
            model_name='configurationsettings',
            name='sidebar_icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/icons/'),
        ),
        migrations.AlterField(
            model_name='configurationsettings',
            name='user_icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/icons/'),
        ),
    ]
