# Generated by Django 2.2.28 on 2024-01-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20240111_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationsettings',
            name='rows_per_page',
            field=models.PositiveIntegerField(default=10, null=True),
        ),
    ]
