# Generated by Django 4.2.9 on 2024-01-13 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_configurationsettings_allow_hosts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationsettings',
            name='allow_hosts',
        ),
    ]
