# Generated by Django 4.2.9 on 2024-01-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_configurationsettings_allow_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationsettings',
            name='allow_host',
            field=models.BooleanField(choices=[(False, 'Off'), (True, 'On')], default=False),
        ),
    ]
