# Generated by Django 4.2.9 on 2024-01-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_configurationsettings_allow_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationsettings',
            name='client_user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
